insert into igrs_user(user, password) values('admin', 'password');
insert into igrs_room(room, client_ip) values('100', '192.168.1.200');
insert into igrs_room(room, client_ip) values('101', '192.168.1.199');
insert into igrs_device_status(room, device_id, attribute, value) values('100', 'welcomemode', 'switch', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('100', 'machine0', 'switch', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('100', 'machine0', 'sig_source', '1');
insert into igrs_device_status(room, device_id, attribute, value) values('100', 'machine0', 'volume', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('100', 'machine1', 'switch', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('100', 'machine1', 'sig_source', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('100', 'machine1', 'volume', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('100', 'led0', 'switch', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('100', 'led1', 'switch', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('100', 'curtain', 'switch', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('101', 'welcomemode', 'switch', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('101', 'machine0', 'switch', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('101', 'machine0', 'sig_source', '1');
insert into igrs_device_status(room, device_id, attribute, value) values('101', 'machine0', 'volume', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('101', 'machine1', 'switch', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('101', 'machine1', 'sig_source', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('101', 'machine1', 'volume', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('101', 'led0', 'switch', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('101', 'led1', 'switch', '0');
insert into igrs_device_status(room, device_id, attribute, value) values('101', 'curtain', 'switch', '0');